---
# Variable setup.
- name: Include OS-Specific variables
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

# Configure Jenkins init settings.
- include_tasks: settings.yml

- name: Add docker jenkins start script
  template:
    src: jenkins.sh
    dest: "{{ jenkins_home }}/jenkins.sh"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775

- name: configure default users
  template:
    src: basic-security.groovy
    dest: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775
  register: jenkins_users_config

- name: configure executors
  template:
    src: set-executors.groovy
    dest: "{{ jenkins_home }}/init.groovy.d/set-executors.groovy"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775

# Update Jenkins and install configured plugins.
- include_tasks: plugins.yml
