---
- name: Get install plugins script from official jenkins image
  get_url:
    url: https://raw.githubusercontent.com/jenkinsci/docker/master/install-plugins.sh
    dest: /usr/local/bin/install-plugins.sh
    mode: '+rx'

- name: Get supporting bash script from official jenkins github
  get_url:
    url: https://raw.githubusercontent.com/jenkinsci/docker/master/jenkins-support
    dest: /usr/local/bin/jenkins-support
    mode: '+rx'

- name: install plugins
  shell: "JENKINS_UC=https://updates.jenkins.io /usr/local/bin/install-plugins.sh {{ item.key }}:{{ item.value }}"
  with_dict: "{{jenkins_plugins}}"

- file:
    path: "{{jenkins_plugins}}/plugins"
    owner: jenkins
    group: jenkins
    mode: 770
    recurse: true
    