---
- name: Ensure dependencies are installed.
  package:
    name:
      - curl
      - libselinux-python
      - unzip
    state: present

- name: Ensure group "jenkins" exists
  group:
    name: jenkins
    state: present

- name: Add jenkins user
  user:
    name: jenkins
    shell: /bin/bash
    group: jenkins

- file:
    path: '/usr/share/jenkins'
    state: directory
    owner: jenkins

- name: Download jenkins war with check (sha256)
  get_url:
    url: https://repo.jenkins-ci.org/public/org/jenkins-ci/main/jenkins-war/{{ jenkins_version }}/jenkins-war-{{ jenkins_version }}.war
    dest: /usr/share/jenkins/jenkins.war
    # checksum: 'sha256:{{ jenkins_checksum }}'

- file: 
    path: "{{ jenkins_home }}"
    owner: jenkins
    recurse: true

- file:
    path: "/usr/share/jenkins/ref"
    owner: jenkins
    recurse: true